name:
  - Greece
  - Russia
  - Netherlands
  - Germany
  - Portugal
  - Spain
  - Italy
  - Croatia
  - France
  - England
  - Switzerland
  - Belgium
  - Bosnia_Herzegovina
  - Algeria
  - Ivory
  - Ghana
  - Cameroon
  - Nigeria
  - Mexico
  - United_States
  - Honduras
  - Costa_Rica
  - Argentina
  - Brazil
  - Chile
  - Uruguay
  - Colombia
  - Ecuador
  - Australia
  - Japan
  - Korea
  - Iran